#!bin/bash

export WT_HOME=/home/wierton

function sedr() {
	sed -i "s/$1/$2/g" `grep -rl "$1"`
	return $?
}

function renamer() {
	rename "s/$1/$2/g" `find . -name "*$1*"`
	return $?
}

function banio() {
	nohup $* </dev/null 1>/dev/null 2>&1 &
	return $?
}

export RCGEN_HOME=${WT_HOME}/rcgen
function wgc() {
	gcc -w $1.c -o $1 -I ${RCGEN_HOME} && ./$1
}


#java
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/bin
PATH="$PATH:$JAVA_HOME"

#android SDK
export ANDROID_HOME=/D/java/android-sdk-linux
PATH="$PATH:/D/java/android-sdk-linux"
PATH="$PATH:/D/java/android-sdk-linux/tools"
PATH="$PATH:/D/java/android-sdk-linux/platform-tools"

#
PATH="$PATH:/opt/gcc-4.3-ls232/bin"

# Vivado
PATH="$PATH:/opt/Xilinx/Vivado/2018.1/bin"

# virtualenv and virtualenvwrapper
#export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
#export WORKON_HOME=$HOME/.virtualenvs
#source /usr/local/bin/virtualenvwrapper.sh

export HADOOP_CLASSPATH=${JAVA_HOME}/lib/tools.jar
PATH="$PATH:/D/hadoop/bin"
# eval $(thefuck --alias)

alias mgcc=mips-linux-gnu-gcc
alias mg++=mips-linux-gnu-g++
alias mstrip=mips-linux-gnu-strip
alias mobjdump=mips-linux-gnu-objdump
alias mreadelf=mips-linux-gnu-readelf

export NOOP_HOME=${WT_HOME}/noop
export AM_HOME=${WT_HOME}/nexus-am
export NAVY_HOME=${WT_HOME}/navy-apps
export MIPS32_NEMU_HOME=${WT_HOME}/nemu-mips32
# export CPU_PATH=${WT_HOME}/noop.17.bin/
export CPU_PATH=${WT_HOME}/lgz-noop/
export CPU_IMG=noop.tcl
export NPC_HOME=${WT_HOME}/noop-lo
export RISCV=/usr/local/riscv

alias vimelf="vim /usr/include/elf.h"
export PATH="$PATH:${RISCV}:/D/IDA_Linux_v6.4"

#export ZSH_THEME=aussiegeek
export ZSH_THEME=wierton

export PATH="$PATH:${WT_HOME}/.local/bin"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

alias jllvm="cd ${WT_HOME}/llvm/llvm/include/llvm"
alias jclang="cd ${WT_HOME}/llvm/llvm/tools/clang"
alias sudo-guard="sudo sh -c exit"
alias open-psmouse="sudo-guard && sudo modprobe -i psmouse"
alias close-psmouse="sudo-guard && sudo modprobe -r psmouse"
alias minecraft="(banio minecraft)"
alias netease-cloud-music="(sudo-guard && sudo nohup netease-cloud-music </dev/null 1>/dev/null 2>&1 &)"
alias vivado="(cd ~/tmp && banio vivado)"
