#!bin/bash

export WT_HOME=/home/wierton

function sedr() {
	sed -i "s/$1/$2/g" `grep -rl "$1"`
	return $?
}

function renamer() {
	rename "s/$1/$2/g" `find . -name "*$1*"`
	return $?
}

function banio() {
	nohup $* </dev/null 1>/dev/null 2>&1 &
	return $?
}

export RCGEN_HOME=${WT_HOME}/rcgen
function wgc() {
	gcc -w $1.c -o $1 -I ${RCGEN_HOME} && ./$1
}


#java
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/bin
PATH="$PATH:$JAVA_HOME"

#android SDK
export ANDROID_HOME=/D/java/android-sdk-linux
PATH="$PATH:/D/java/android-sdk-linux"
PATH="$PATH:/D/java/android-sdk-linux/tools"
PATH="$PATH:/D/java/android-sdk-linux/platform-tools"

# loongson gcc
PATH="$PATH:/opt/gcc-4.3-ls232/bin"

# Vivado
PATH="$PATH:/opt/Xilinx/Vivado/2018.1/bin"
# PATH="$PATH:/opt/Xilinx/Vivado/2017.4/bin"
alias vivado17="/opt/Xilinx/Vivado/2017.4/bin/vivado"
alias vivado-batch="vivado -nolog -nojournal -notrace -mode batch -source"

# virtualenv and virtualenvwrapper
#export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
#export WORKON_HOME=$HOME/.virtualenvs
#source /usr/local/bin/virtualenvwrapper.sh

export HADOOP_CLASSPATH=${JAVA_HOME}/lib/tools.jar
PATH="$PATH:/D/hadoop/bin"
# eval $(thefuck --alias)

alias mld=mips-linux-gnu-ld
alias mgcc=mips-linux-gnu-gcc
alias mg++=mips-linux-gnu-g++
alias mstrip=mips-linux-gnu-strip
alias mobjdump=mips-linux-gnu-objdump
alias mobjcopy=mips-linux-gnu-objcopy
alias mreadelf=mips-linux-gnu-readelf
alias mas=mips-linux-gnu-as
alias mar=mips-linux-gnu-ar

alias nemu-mips32=${WT_HOME}/nemu-mips32/build/nemu

export NOOP_HOME=${WT_HOME}/noop
export AM_HOME=${WT_HOME}/nexus-am
export NAVY_HOME=${WT_HOME}/navy-apps
export MIPS32_NEMU_HOME=${WT_HOME}/nemu-mips32
# export CPU_PATH=${WT_HOME}/noop.17.bin/
export CPU_PATH=${WT_HOME}/lgz-noop/
export CPU_IMG=noop.tcl
# export NPC_HOME=${WT_HOME}/noop-lo
export NSCSCC_HOME=${WT_HOME}/nscscc2018

alias vimelf="vim /usr/include/elf.h"
export PATH="$PATH:/D/IDA_Linux_v6.4"

#export ZSH_THEME=aussiegeek
export ZSH_THEME=wierton

export PATH="$PATH:${WT_HOME}/.local/bin"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

alias jllvm="cd ${WT_HOME}/llvm/llvm/include/llvm"
alias jclang="cd ${WT_HOME}/llvm/llvm/tools/clang"
alias sudo-guard="sudo sh -c exit"
alias open-psmouse="sudo-guard && sudo modprobe -i psmouse"
alias close-psmouse="sudo-guard && sudo modprobe -r psmouse"
alias minecraft="(banio minecraft)"
alias netease-cloud-music="(sudo-guard && banio sudo netease-cloud-music)"
alias gtkterm="(sudo-guard && sudo gtkterm --port /dev/ttyACM0 --speed 115200 &)"
# alias vivado="(cd ~/tmp && banio vivado)" # the relative path

# FPGA
IP=192.168.1.17
alias ssh-cpu="sshpass -p root ssh root@$IP"
alias serial-cpu="sudo minicom -D /dev/ttyACM0 -c on"
alias cpu-out="sshpass -p root ssh -t root@$IP 'rm cpu.out && minicom -D /dev/ttyPS1 -c on -C cpu.out'"

function gs() {
  if [ $# -eq 0 ]; then
    ssh -X -C gs@192.168.1.100 "cd $PWD; zsh -l"
  else
	ssh -X -C gs@192.168.1.100 "cd $PWD; $*"
  fi
  return $?
}

function upload() {
	sshpass -p root scp $1 root@$IP:~/
}

function mips-as() {
	name=`basename -s .S $1`
	mips-linux-gnu-as -EL $name.S -o $name.o
	mips-linux-gnu-ld -EL -T $WT_HOME/loader.ld $name.o -o $name
	mips-linux-gnu-objdump -D $name > $name.asm
	mips-linux-gnu-objcopy -O binary $name $name.bin
	truncate -s %8 $name.bin
	hexdump -ve '2/ "%08x " "\n"' $name.bin | awk '{print $2$1}' > $name.bin.txt
}

function bin2mif() {(
  l=4
  while [ -n "$1" ]; do
	case "$1" in
	  -h) echo bin2mif -l length filename;
		  exit 0 ;;
	  -l) l=$2
		  shift ;;
	   *) f=$1
		 ;;
	esac
	shift
  done

  if [ -n "$f" ]; then
	hexdump -ve 1/$l\ \"%0$(( $l*2 ))x\\n\" $f |
	  sed 's/0/0000/g;s/1/0001/g;s/2/0010/g;s/3/0011/g;
	       s/4/0100/g;s/5/0101/g;s/6/0110/g;s/7/0111/g;
	       s/8/1000/g;s/9/1001/g;s/a/1010/g;s/b/1011/g;
	       s/c/1100/g;s/d/1101/g;s/e/1110/g;s/f/1111/g;'
  else
	echo "no input files"
  fi
)}

function bin2txt() {(
  l=4
  while [ -n "$1" ]; do
	case "$1" in
	  -h) echo bin2txt -l length filename;
		  exit 0 ;;
	  -l) l=$2
		  shift ;;
	   *) f=$1
		 ;;
	esac
	shift
  done

  if [ -n "$f" ]; then
	hexdump -ve 1/$l\ \"%0$(( $l*2 ))x\ \" $f | fmt --width 60
  else
	echo "no input files"
  fi
)}

function bin2coe() {(
  l=4
  while [ -n "$1" ]; do
	case "$1" in
	  -h) echo bin2coe -l length filename;
		  exit 0 ;;
	  -l) l=$2
		  shift ;;
	   *) f=$1
		 ;;
	esac
	shift
  done

  if [ -n "$f" ]; then
	hexdump -ve 1/$l\ \"%0$(( $l*2 ))x\\n\" $f | sed 1i'memory_initialization_radix = 16;\nmemory_initialization_vector ='
  else
	echo "no input files"
  fi
)}

